### ISSUE TITLE
Ingress for SSO proxy

### ISSUE THREAD

**Issue by pyToshka** [aleveille/octant-dashboard-turnkey#4]
Hi, after deployment chart, i configured 
```
keycloakGatekeeper:
  enabled: true
  url: https://keycloak.local/auth/realms/master
  clientId: testcli
  clientSecret: <secret>
  proxyPort: 4999

```
But as I can see ingres for octant https://example.com/octant redirect me to https://example.com/oauth/authorize?state=dadadsd which not evaliable. 
What i do wrong? Thank you in advance
