### ISSUE TITLE
Ingress is only usable with root path "/"

### ISSUE THREAD

**Issue by deschmih** [aleveille/octant-dashboard-turnkey#8]
Hey,

I really like this project and it work with less effort in cluster. Thank's for that.
In cluster I  use a nginx ingress controller and I have setup these controller in `value.yaml` like this:
```
...
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
  - host: ""
    paths: 
    - /sew/octant-ui/(.*)
... 
```

See what happens:
Ingress is responding with HTTP_STATUS_CODE_OK, 
![image](https://user-images.githubusercontent.com/49398923/98912815-e50ea980-24c6-11eb-870d-64b89f26cb47.png)

but while accessing the octant-html-elements,

![image](https://user-images.githubusercontent.com/49398923/98912860-f22b9880-24c6-11eb-914e-7c06f276673e.png)

 a wrong base-path is used.

![image](https://user-images.githubusercontent.com/49398923/98912880-f8217980-24c6-11eb-99f8-a0af8ed29fb4.png)

Is there a way to fix this?
Thanks in advance.

Regards,
Michael
